version: "3.3"
services:
  waterfall:
    container_name: waterfall
    # Use a proper commit hash for specific deployments.
    image: ghcr.io/matrix-org/waterfall:sha-b64edee
    network_mode: host
    restart: always
    environment:
      # Set the `CONFIG` to the configuration you want.
      CONFIG: |
        matrix:
          homeserverUrl: "http://localhost:8008"
          userId: "@sfu:shadowfax"
          accessToken: "..."
        conference:
          heartbeat:
            timeout: 30
            interval: 30
        webrtc:
          simulcast: true
        telemetry:
          package: "waterfall"
          id: "instance_test"
          otlp:
            host: "localhost:4318"
            secure: false
          jaegerUrl: "http://localhost:14268/api/traces"
